# Parameter Example

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 instance Key Pair to access SSH connection

  Wordpress:
    Type: String
    NoEcho: true
    Default: Admin
    MinLength: 1
    MaxLength: 16
    AllowPattern: "[a-zA-Z][a-zA-Z0-9]*"

  WebServerPort:
    Default: 8888
    Type: number
    MinValue: 1
    MaxValue: 65535
    Description: TPC/IP Port for web Server 

  InstanceTypeParameter:
    Description: Enter t3.micro t3.small t3.medium instance use in this template
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium

  DBPwd:
    NoEcho: true
    Description: Enter DB Password
    Type: String
    MinLength: 1
    MaxLength: 41
    AllowedPattern: ^[a-zA-Z0-9]*$

  DBSubnetIpBlocks:
    Description: "Comma delimeter list of three CIDR Block"
    Type: CommaDelimitedList
    Default: "10.0.48.0/24, 10.0.112.0/24, 10.0.176.0/24"
    