AWSTemplateFormatVersion: 2010-09-09
Description: A Simple EC2 instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ae8f15ae66fe8cda
      InstanceType: t3.small
      KeyName: Demo-k
      SecurityGroupIds: 
        - sg-07c81db300079ffc3
      SubnetId: subnet-038c7443c911ebdc1