AWSTemplateFormatVersion: 2010-09-09
Description: A Simple EC2 instance
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Enter Key name
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Description: Enter Instance type
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Enter Vpc Id
    Default: vpc-0b59960c2fc09f7cd
    AllowedValues:
      - vpc-0b59960c2fc09f7cd
      - vpc-08ced18c894b28aa2
      - vpc-045a4913e9fee88d1
      - vpc-0356927f239643c17
      - vpc-0b59960c2fc09f7cd
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Enter Subnet Id
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Enter Security Group Id
  IAMRole:
    Type: String
    Default: ec2-secret-execution-role
    Description: Enter IAM Role
    AllowedValues:
      - ec2-secret-execution-role
      - NDS-Cync-Dev-EC2-SSM-Role
      - ecrecsfullaccess
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ae8f15ae66fe8cda
      InstanceType: t3.small
      KeyName: Demo-k
      SecurityGroupIds: 
        - sg-07c81db300079ffc3
      SubnetId: subnet-038c7443c911ebdc1
      